[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "DEMO_DB_DEV"
account = "hapeljg-job29427"
user = "DEMO_USER"
password = "SuccessPersist@479"
